Repository cse110-fa22-group13/cse110-fa22-group13, pull requests merged in 2022-11, with the labels that each got.

#43 Update 110622-postPitchMeeting.md
  admin/meetings/110622-postPitchMeeting.md
Labels: documentation

#53 Changed from using docsify.js to jsdocs
  specs/adrs/codeConventionADR.md
Labels: documentation

#63 Add pipeline demo video
  admin/cipipeline/phase1.mp4
Labels: documentation, meetings

#65 Created meeting minutes for sprint review and retrospective
  admin/meetings/111222-retrospective.md
  admin/meetings/111222-sprint-1-review.md
Labels: documentation

#72 Pull request for Homepage HTML/CSS with errors fixed
  source/homepage/1.png
  source/homepage/2.png
  source/homepage/3.png
  source/homepage/4.png
  source/homepage/5.png
  source/homepage/6.png
  source/homepage/7.png
  source/homepage/8.png
  source/homepage/9.png
  source/homepage/Books-Icon.png
  source/homepage/Checklist-Icon.jpg
  source/homepage/Internet-Cloud.png
  source/homepage/Logo.svg
  source/homepage/Roboto-Regular.ttf
  source/homepage/index.css
  source/homepage/index.html
Labels: framework, CSS, HTML

#77 Add Book Entries page and updated sources
  source/bookEntries/README.md
  source/bookEntries/bookEntries.css
  source/bookEntries/bookEntries.html
  source/bookEntries/placeholder.txt
  source/homepage/index.css
  source/homepage/index.html
  source/resources/fonts/Roboto-Regular.ttf
  source/resources/images/book-covers/all-my-rage-cover.png
  source/resources/images/book-covers/boys-from-biloxi-cover.png
  source/resources/images/book-covers/fairy-tale-cover.png
  source/resources/images/book-covers/fire-and-blood-cover.png
  source/resources/images/book-covers/it-ends-with-us-cover.png
  source/resources/images/book-covers/never-finished-cover.png
  source/resources/images/book-covers/spare-cover.png
  source/resources/images/book-covers/ugly-love-cover.png
  source/resources/images/book-covers/what-my-bones-know-cover.png
Labels: framework, CSS, HTML

#90 Update the main branch with new meeting minutes and Adrs
  admin/meetings/pre-sprint-meetings/100822-kickOffMeeting.md
  admin/meetings/pre-sprint-meetings/101522-videoAndBrandingMeeting.md
  admin/meetings/pre-sprint-meetings/102222-brainstorm.md
  admin/meetings/pre-sprint-meetings/102622-pitchMeeting.md
  admin/meetings/pre-sprint-meetings/103022-pitchMeetingPart2.md
  admin/meetings/pre-sprint-meetings/110622-postPitchMeeting.md
  admin/meetings/pre-sprint-meetings/111922-ADRsMeeting.md
  admin/meetings/retrospectives/111222-retrospective.md
  admin/meetings/retrospectives/111922-retrospective.md
  admin/meetings/retrospectives/JSONs Retrospective 2.pdf
  admin/meetings/sprint-meetings/111222-sprint-1-review.md
  admin/meetings/sprint-meetings/111922-Sprint2Meeting.md
  specs/adrs/contentIntegrationChoicesADR.md
  specs/adrs/defOfDoneADR.md
  specs/adrs/toolsADR.md
Labels: documentation, ADRs, meetings

#93 Update documentationToPages.yml
  .github/workflows/documentationToPages.yml
Labels: bug, documentation, CI/CD

#99 GitHub actions auto tester
  .github/workflows/autoTester.yml
  .github/workflows/helloWorldWorkFlow.yml
  admin/placeholder file.txt
  source/homepage/placeholder.txt
  source/placeholder file.txt
  source/resources/js/BookEntry.test.js
Labels: enhancement, CI/CD, change

#101 implemented responsive feature and added some basic comments
  source/bookEntries/bookEntries.css
  source/bookEntries/bookEntries.html
  source/homepage/index.css
  source/homepage/index.html
Labels: enhancement, CSS

#104 Update README.md team.md path to full path
  README.md
  source/resources/js/BookEntry.js
Labels: change, defect

#116 Create linter.yml
  .github/workflows/linter.yml
Labels: enhancement, CI/CD

#118 Re-pull request after changes to meeting minutes
  admin/meetings/general-meetings/100822-kickOffMeeting.md
  admin/meetings/general-meetings/101522-videoAndBrandingMeeting.md
  admin/meetings/general-meetings/102222-brainstorm.md
  admin/meetings/general-meetings/102622-pitchMeeting.md
  admin/meetings/general-meetings/103022-pitchMeetingPart2.md
  admin/meetings/general-meetings/110622-postPitchMeeting.md
  admin/meetings/general-meetings/111922-ADRsMeeting.md
  admin/meetings/retrospectives/111922-retrospective.md
  admin/meetings/retrospectives/112822-retrospective.md
  admin/meetings/retrospectives/retrospective3pic.png
  admin/meetings/sprint-meetings/111922-sprint-2-review.md
  admin/meetings/sprint-meetings/112822-sprint-3-review.md
  specs/adrs/webComponentsADR.md
Labels: documentation, meetings

#126 fix html css linter bug
  package-lock.json
  package.json
Labels: CI/CD, defect

#129 Fix csshtml linter issue
  .eslintrc.js
Labels: CI/CD, change, defect

#139 Change deploying to also deploy app
  .github/workflows/documentationToPages.yml
  source/homepage/index.html
Labels: CI/CD, change

#140 Update index.html
  source/homepage/index.html
Labels: CI/CD, defect

#141 Update README.md
  README.md
Labels: CI/CD, change

#142 Update README.md
  README.md
Labels: CI/CD
