Repository cse110-fa22-group13/cse110-fa22-group13, pull requests merged in 2022-12, with the labels that each got.

#144 Update documentationToPages.yml
  .github/workflows/documentationToPages.yml
Labels: CI/CD, change

#145 Implemented features and some minor changes
  source/bookEntries/bookEntries.css
  source/bookEntries/bookEntries.html
  source/bookEntries/bookEntries.js
  source/resources/js/BookEntry.js
  source/resources/js/BookList.js
Labels: JS, priority, defect

#146 Implemented CRUD features
  .eslintrc.js
  package-lock.json
  package.json
  source/bookEntries/bookEntries.css
  source/bookEntries/bookEntries.html
  source/bookEntries/bookEntries.js
  source/resources/js/BookEntry.js
  source/resources/js/BookEntry.test.js
  source/resources/js/BookList.js
Labels: JS, priority

#147 fixed the issue with inputting wrong values
  source/resources/js/BookEntry.js
  source/resources/js/BookList.js
Labels: JS, change

#148 add link to docs and app from readme
  README.md
Labels: change

#149 Change links for image to be hardcoded for deploying to pages
  source/bookEntries/bookEntries.html
  source/homepage/index.html
  source/resources/js/BookEntry.js
Labels: change

#152 Fix more link issues for GitHub pages
  .eslintignore
  playwright-report/index.html
  source/bookEntries/bookEntries.html
Labels: change, defect

#153 Delete playwright-report directory
  playwright-report/index.html
Labels: change

#154 Fix link home page button
  .eslintignore
  source/bookEntries/bookEntries.html
Labels: change

#155 Roadmap/ADRs are 100% up to date
  specs/Roadmap.pdf
  specs/adrs/defOfDoneADR.md
  specs/adrs/toolsADR.md
  specs/roadmap.pdf
Labels: ADRs, roadmap, change

#156 basic unit testing
  source/bookEntries/bookEntries.test.js
  source/resources/js/BookEntry.test.js
  source/resources/js/BookList.test.js
Labels: CI/CD, JS

#159 E2e testing branch
  .github/workflows/autoTester.yml
  README.md
  package-lock.json
  package.json
  source/bookEntries/bookEntries.css
  source/bookEntries/bookEntries.html
  source/bookEntries/bookEntries.js
  source/homepage/index.html
  source/resources/e2eTests/applicationE2ETests.test.js
  source/resources/js/BookEntry.js
  source/resources/js/BookEntry.test.js
  source/resources/js/BookList.js
  specs/system diagrams/inheritance.drawio.png
  specs/system diagrams/uml_activity_diagram.drawio.png
Labels: documentation, enhancement, system diagram, CI/CD, change

#161 quick fixed the bug
  source/resources/e2eTests/applicationE2ETests.test.js
  source/resources/js/BookEntry.js
Labels: JS, change

#162 Update README.md
  README.md
Labels: change

#163 Updated HTML and CSS
  source/bookEntries/bookEntries.css
  source/bookEntries/bookEntries.html
  source/bookEntries/bookEntries.js
  source/bookEntries/bookEntries.test.js
  source/homepage/index.css
  source/homepage/index.html
  source/resources/e2eTests/applicationE2ETests.test.js
  source/resources/js/BookEntry.js
  source/resources/js/BookEntry.test.js
  source/resources/js/BookList.js
  source/resources/js/BookList.test.js
Labels: CSS, HTML, change

#167 Update README.md
  README.md
Labels: change

#168 Update README.md
  README.md
Labels: change

#171 Onboard update
  README.md
  admin/onboard.md
Labels: documentation
